TEXTS = {}

TEXTS["EN"] = {
    "title": "Survey Data Analyzer",
    "subtitle": "Interactive survey data analysis with statistics, visuals, and text processing",
    "upload_subheader": "Upload Data",
    "upload_label": "Upload CSV or Excel file",
    "data_preview": "Data Preview",
    "data_preview_subtitle": "Showing first 1000 rows",
    "text_processing_subheader": "Text Processing",
    "text_columns_detected": "Detected text columns",
    "select_text_col": "Select text column",
    "no_text_columns": "No text columns available",
    "text_processing_note": "Text is lowercased, punctuation removed, and English stopwords filtered",
    "sample_tokens": "Sample Tokens",
    "top_words": "Top Words",
    "stats_subheader": "Descriptive Statistics",
    "select_numeric_col": "Select numeric column",
    "no_numeric_cols": "No numeric columns available",
    "desc_stats": "Descriptive Statistics",
    "freq_table_subheader": "Frequency Table",
    "select_categorical_col": "Select categorical column",
    "no_categorical_cols": "No categorical columns available",
    "freq_count": "Frequency",
    "freq_percent": "Percentage",
    "visual_subheader": "Visualization",
    "histogram": "Histogram",
    "boxplot": "Boxplot",
    "correlation_subheader": "Correlation & Tests",
    "pearson_header": "Pearson Correlation",
    "spearman_header": "Spearman Correlation",
    "chi_header": "Chi-square Test",
    "select_x_numeric": "Select X numeric",
    "select_y_numeric": "Select Y numeric",
    "not_enough_numeric": "Not enough numeric columns",
    "pearson_result": "Pearson Result",
    "spearman_result": "Spearman Result",
    "corr_coef": "Correlation Coefficient",
    "p_value": "p-value",
    "interpretation": "Interpretation",
    "select_x_cat": "Select X categorical",
    "select_y_cat": "Select Y categorical",
    "not_enough_categorical": "Not enough categorical columns",
    "chi_square_result": "Chi-square Result",
    "chi_square_stat": "Chi-square Statistic",
    "chi_square_df": "Degrees of Freedom",
    "chi_square_p": "p-value",
    "alpha_note": "Alpha = 0.05",
    "significant_assoc": "Significant association detected",
    "no_significant_assoc": "No significant association detected",
    "corr_direction_positive": "Positive",
    "corr_direction_negative": "Negative",
    "corr_direction_zero": "No direction",
    "corr_strength_none": "None",
    "corr_strength_weak": "Weak",
    "corr_strength_moderate": "Moderate",
    "corr_strength_strong": "Strong",
    "warning_select_valid": "Please select valid columns",
    "nav_desc": "Descriptive",
    "nav_visual": "Visualization",
    "nav_corr": "Correlation",
    "nav_text": "Text",
    "export_title": "Export Report",
    "export_desc": "Download analysis summary as PDF",
    "export_button": "Generate PDF",
    "export_filename": "survey_report.pdf",
    "pdf_title": "Survey Analysis Report",
    "pdf_section_numdist": "Numeric Distributions",
    "pdf_section_scatter": "Scatter Plots",
    "pdf_section_catbar": "Categorical Bar Charts",
    "pdf_section_numfull": "Numeric Statistics",
    "pdf_section_catfreq": "Categorical Frequencies",
    "pdf_section_corr": "Correlation Analysis",
    "pdf_section_text": "Text Analysis",
    "pdf_notext": "No text analysis available",
    "no_file": "Please upload a data file to continue",
    "bar_chart_top20": "Top 20 Categories",
    "pdf_meta_rows": "Rows",
    "pdf_meta_cols": "Columns",
    "group_info": "Group Information",
    "statistic_label": "Statistic",
    "p_value_label": "p-value",
    "deviate_normal": "Data deviates from normality",
    "no_deviate_normal": "Data does not deviate from normality",
    "not_enough_normality": "Not enough data for normality test"
}

for lg in ["ID", "JP", "KR", "CN", "AR"]:
    TEXTS[lg] = TEXTS["EN"].copy()

TEXTS["PT"] = TEXTS["EN"].copy()
TEXTS["PT"]["title"] = "Analisador de Dados de Pesquisa"
TEXTS["PT"]["export_filename"] = "relatorio_pesquisa.pdf"
